# Generated by Django 4.0.4 on 2022-05-13 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sant',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='santo/'),
        ),
        migrations.CreateModel(
            name='PurvashramDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('native_place', models.CharField(blank=True, max_length=100, null=None)),
                ('study', models.CharField(blank=True, max_length=100, null=None)),
                ('sant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sant.sant')),
            ],
        ),
        migrations.CreateModel(
            name='DikshaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Bhagvadi', 'Bhagvadi'), ('Parshadi', 'Parshadi'), ('Sadhak', 'Sadhak')], max_length=10)),
                ('Date', models.DateField(blank=None, null=None)),
                ('place', models.CharField(blank=None, max_length=25, null=None)),
                ('event', models.CharField(blank=None, max_length=50, null=None)),
                ('sant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sant.sant')),
            ],
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='attachments/')),
                ('photolink', models.URLField(blank=True, max_length=1500, null=None)),
                ('discripttion', models.CharField(max_length=1500)),
                ('sant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sant.sant')),
            ],
        ),
        migrations.CreateModel(
            name='AnuvrutiDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromYear', models.CharField(choices=[('Present', 'Present'), ('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=7)),
                ('toYear', models.CharField(choices=[('Present', 'Present'), ('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=7)),
                ('place', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('seva', models.CharField(max_length=20)),
                ('sant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sant.sant')),
            ],
        ),
    ]
