# Generated by Django 4.0.4 on 2022-05-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sant', '0004_alter_attachments_sant_alter_purvashramdetails_sant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SantRead',
            fields=[
            ],
            options={
                'verbose_name': 'Santo',
                'verbose_name_plural': 'Santo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Sant.sant',),
        ),
    ]
