# Generated by Django 4.0.4 on 2022-05-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sant', '0006_alter_sant_options_alter_santread_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuvrutidetails',
            options={'verbose_name': 'અનુવૃતિ વિગત', 'verbose_name_plural': 'અનુવૃતિ વિગત'},
        ),
        migrations.AlterModelOptions(
            name='attachments',
            options={'verbose_name': 'ફોટો', 'verbose_name_plural': 'ફોટો'},
        ),
        migrations.AlterModelOptions(
            name='dikshadetails',
            options={'verbose_name': 'દીક્ષા વિગત', 'verbose_name_plural': 'દીક્ષા વિગત'},
        ),
        migrations.AlterModelOptions(
            name='purvashramdetails',
            options={'verbose_name': 'પૂર્વાશ્રમની વિગત', 'verbose_name_plural': 'પૂર્વાશ્રમની વિગત'},
        ),
        migrations.AlterModelOptions(
            name='santread',
            options={'verbose_name': 'પૂ.સંત વિગત', 'verbose_name_plural': 'પૂ.સંત વિગત'},
        ),
        migrations.AddField(
            model_name='sant',
            name='remark',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='વિશેષ વિગત'),
        ),
        migrations.AlterField(
            model_name='anuvrutidetails',
            name='fromYear',
            field=models.CharField(choices=[('Present', 'Present'), ('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=7, verbose_name='શરૂઆત'),
        ),
        migrations.AlterField(
            model_name='anuvrutidetails',
            name='place',
            field=models.CharField(max_length=20, verbose_name='સ્થળ/મંદિર'),
        ),
        migrations.AlterField(
            model_name='anuvrutidetails',
            name='post',
            field=models.CharField(max_length=20, verbose_name='પદ'),
        ),
        migrations.AlterField(
            model_name='anuvrutidetails',
            name='seva',
            field=models.CharField(max_length=20, verbose_name='વિભાગ'),
        ),
        migrations.AlterField(
            model_name='anuvrutidetails',
            name='toYear',
            field=models.CharField(choices=[('Present', 'Present'), ('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=7, verbose_name='અંત'),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='discripttion',
            field=models.CharField(max_length=1500, verbose_name='વર્ણન'),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='photo',
            field=models.ImageField(upload_to='attachments/', verbose_name='ફોટો'),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='photolink',
            field=models.URLField(blank=True, max_length=1500, null=None, verbose_name='લિંક'),
        ),
        migrations.AlterField(
            model_name='dikshadetails',
            name='Date',
            field=models.DateField(blank=None, null=None, verbose_name='દીક્ષા દિન'),
        ),
        migrations.AlterField(
            model_name='dikshadetails',
            name='event',
            field=models.CharField(blank=None, max_length=50, null=None, verbose_name='સમૈયા/ઉત્સવ'),
        ),
        migrations.AlterField(
            model_name='dikshadetails',
            name='place',
            field=models.CharField(blank=None, max_length=25, null=None, verbose_name='સ્થળ'),
        ),
        migrations.AlterField(
            model_name='dikshadetails',
            name='type',
            field=models.CharField(choices=[('Bhagvadi', 'Bhagvadi'), ('Parshadi', 'Parshadi'), ('Sadhak', 'Sadhak')], max_length=10, verbose_name='પ્રકાર'),
        ),
        migrations.AlterField(
            model_name='purvashramdetails',
            name='name',
            field=models.CharField(max_length=100, verbose_name='નામ'),
        ),
        migrations.AlterField(
            model_name='purvashramdetails',
            name='native_place',
            field=models.CharField(blank=True, max_length=100, null=None, verbose_name='વતન'),
        ),
        migrations.AlterField(
            model_name='purvashramdetails',
            name='study',
            field=models.CharField(blank=True, max_length=100, null=None, verbose_name='અભ્યાસ'),
        ),
    ]
