# Generated by Django 3.0 on 2022-05-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sant', '0007_alter_anuvrutidetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dikshadetails',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='દીક્ષિત નામ'),
        ),
        migrations.AlterField(
            model_name='anuvrutidetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dikshadetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purvashramdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
